# Generated by Django 5.2.7 on 2025-10-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_ins', '0002_check_in_day_type_check_in_relaxed_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_in',
            name='description',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
