# Generated by Django 5.2.7 on 2025-10-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_ins', '0003_alter_check_in_description_alter_check_in_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check_in',
            name='category',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='coping_action',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='day_type',
            field=models.CharField(default='Not specified', max_length=1000),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='description',
            field=models.CharField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='relaxed_today',
            field=models.CharField(default='Not specified', max_length=1000),
        ),
        migrations.AlterField(
            model_name='check_in',
            name='title',
            field=models.CharField(max_length=10000, unique=True),
        ),
    ]
